# Generated by Django 5.1.2 on 2024-10-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontype',
            name='name',
        ),
        migrations.AddField(
            model_name='lessontype',
            name='duration',
            field=models.CharField(choices=[('20 minutes', '20 minutes'), ('30 minutes', '30 minutes'), ('45 minutes', '45 minutes'), ('60 minutes', '60 minutes')], default='20 minutes', max_length=20),
        ),
    ]
