# Generated by Django 5.1.2 on 2024-10-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontype',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='duration',
            field=models.CharField(choices=[('20', '20 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], max_length=20),
        ),
    ]
