# Generated by Django 5.1.2 on 2024-10-28 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lessontype_name_lessontype_sale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lessontype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student')),
            ],
        ),
    ]
