# Generated by Django 5.1.2 on 2024-10-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlesson',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
