# Generated by Django 5.1.2 on 2024-10-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_alter_lessontype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student'),
        ),
    ]
