# Generated by Django 5.1.2 on 2024-10-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_studentlesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='StudentLesson',
        ),
    ]
