# Generated by Django 5.1.2 on 2024-10-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_alter_lessontype_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredits',
            name='lesson_type',
        ),
        migrations.RemoveField(
            model_name='usercredits',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScheduledLesson',
        ),
        migrations.DeleteModel(
            name='UserCredits',
        ),
    ]
