# Generated by Django 5.1.2 on 2024-11-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_remove_studentprofile_preferred_lesson_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='lesson_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='duration',
            field=models.CharField(choices=[('20', '20 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes'), ('0', '0 minutes'), ('1', '1 minutes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='lesson_duration',
            field=models.CharField(choices=[('20', '20 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes'), ('0', '0 minutes'), ('1', '1 minute')], default='30', max_length=20),
        ),
    ]
