# Generated by Django 5.1.2 on 2024-11-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_studentprofile_lesson_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='duration',
            field=models.CharField(choices=[('20', '20 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes'), ('0', '0 minutes'), ('1', '1 minute')], max_length=20),
        ),
    ]
