# Generated by Django 5.1.2 on 2024-11-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0026_alter_lessontype_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='lesson_duration',
            field=models.CharField(choices=[('20', '20 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes')], default='30', max_length=20),
        ),
    ]
