# Generated by Django 5.1.2 on 2024-11-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_alter_lessontype_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='lesson_history',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='low_credit_email',
            field=models.TextField(blank=True, default='You have only 1 lesson credit left. Please purchase more.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='no_credit_email',
            field=models.TextField(blank=True, default='You have no lesson credits left. Please purchase more.'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='lesson_duration',
            field=models.CharField(choices=[('20', '20 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes'), ('0', '0 minutes'), ('1', '1 minute')], default='30', max_length=20),
        ),
    ]
