# Generated by Django 5.1.2 on 2024-11-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0029_remove_studentprofile_lesson_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='lesson_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
