# Generated by Django 5.1.2 on 2024-11-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0030_studentprofile_lesson_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='added_credit_email',
            field=models.TextField(blank=True, default='You have purchased lesson credits.'),
        ),
    ]
