# Generated by Django 5.1.2 on 2024-11-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0031_studentprofile_added_credit_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='added_credit_email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='low_credit_email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='no_credit_email',
        ),
    ]
